/*

 ACE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : simple.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define aceWidth 20
#define aceHeight 18
#define aceBank 0

#define ace acePLN0
extern unsigned char acePLN0[];
extern unsigned char acePLN1[];

/* End of ACE.H */
