/*

 BI.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : simple.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define biWidth 20
#define biHeight 18
#define biBank 0

#define bi biPLN0
extern unsigned char biPLN0[];
extern unsigned char biPLN1[];

/* End of BI.H */
