/*

 ENBY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : simple.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define enbyWidth 20
#define enbyHeight 18
#define enbyBank 0

#define enby enbyPLN0
extern unsigned char enbyPLN0[];
extern unsigned char enbyPLN1[];

/* End of ENBY.H */
