/*

 FLAGTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 25

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define flagtilesBank 0

/* Super Gameboy palette 0 */
#define flagtilesSGBPal0c0 6076
#define flagtilesSGBPal0c1 8935
#define flagtilesSGBPal0c2 6596
#define flagtilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define flagtilesSGBPal1c0 6076
#define flagtilesSGBPal1c1 8935
#define flagtilesSGBPal1c2 6596
#define flagtilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define flagtilesSGBPal2c0 6076
#define flagtilesSGBPal2c1 8935
#define flagtilesSGBPal2c2 6596
#define flagtilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define flagtilesSGBPal3c0 6076
#define flagtilesSGBPal3c1 8935
#define flagtilesSGBPal3c2 6596
#define flagtilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define flagtilesCGBPal0c0 32767
#define flagtilesCGBPal0c1 219
#define flagtilesCGBPal0c2 24189
#define flagtilesCGBPal0c3 30473

/* Gameboy Color palette 1 */
#define flagtilesCGBPal1c0 21983
#define flagtilesCGBPal1c1 11903
#define flagtilesCGBPal1c2 20890
#define flagtilesCGBPal1c3 12308

/* Gameboy Color palette 2 */
#define flagtilesCGBPal2c0 607
#define flagtilesCGBPal2c1 31
#define flagtilesCGBPal2c2 3407
#define flagtilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define flagtilesCGBPal3c0 959
#define flagtilesCGBPal3c1 1666
#define flagtilesCGBPal3c2 28888
#define flagtilesCGBPal3c3 22817

/* Gameboy Color palette 4 */
#define flagtilesCGBPal4c0 18670
#define flagtilesCGBPal4c1 18591
#define flagtilesCGBPal4c2 32420
#define flagtilesCGBPal4c3 14364

/* Gameboy Color palette 5 */
#define flagtilesCGBPal5c0 29045
#define flagtilesCGBPal5c1 5119
#define flagtilesCGBPal5c2 14798
#define flagtilesCGBPal5c3 11278

/* Gameboy Color palette 6 */
#define flagtilesCGBPal6c0 6076
#define flagtilesCGBPal6c1 8935
#define flagtilesCGBPal6c2 6596
#define flagtilesCGBPal6c3 4228

/* Gameboy Color palette 7 */
#define flagtilesCGBPal7c0 6076
#define flagtilesCGBPal7c1 8935
#define flagtilesCGBPal7c2 6596
#define flagtilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char flagtilesCGB[];
/* Start of tile array. */
extern unsigned char flagtiles[];

/* End of FLAGTILES.H */
