/*

 GAY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : simple.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gayWidth 20
#define gayHeight 18
#define gayBank 0

#define gay gayPLN0
extern unsigned char gayPLN0[];
extern unsigned char gayPLN1[];

/* End of GAY.H */
