/*

 LESBO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : simple.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lesboWidth 20
#define lesboHeight 18
#define lesboBank 0

#define lesbo lesboPLN0
extern unsigned char lesboPLN0[];
extern unsigned char lesboPLN1[];

/* End of LESBO.H */
