/*

 PAN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : simple.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define panWidth 20
#define panHeight 18
#define panBank 0

#define pan panPLN0
extern unsigned char panPLN0[];
extern unsigned char panPLN1[];

/* End of PAN.H */
