/*

 TRANSFLAG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : simple.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define transflagWidth 20
#define transflagHeight 18
#define transflagBank 0

#define transflag transflagPLN0
extern unsigned char transflagPLN0[];
extern unsigned char transflagPLN1[];

/* End of TRANSFLAG.H */
